import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import React from 'react';
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>standard robot</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <p>
                        &nbsp;
                        <code className={styles.code}>ideally, evacuate - COMING 2023</code>
                    </p>
                </div>

                <div className={styles.center}>
                    <Image
                        className={styles.logo}
                        src="/next.svg"
                        alt="Next.js Logo"
                        width={180}
                        height={37}
                        priority
                    />
                    <div className={styles.thirteen}>
                        <Image
                            src="/thirteen.svg"
                            alt="13"
                            width={40}
                            height={31}
                            priority
                        />
                    </div>
                </div>
                <div className={inter.className}>
                    <div>
                        <h1 className={inter.className}><code className={styles.code}>$ whoami</code></h1>
                        <div className={styles.center}>
                            <p className={inter.className}>Online, I go by the name standardrobot. I enjoy making electronic music, programming, and playing video games. <br />Professionally, I&lsquo;m a cyber systems engineer with a strong interest in offensive security.<br />This project came about because I bought this domain to secure the name. I'll be using the opportunity as a trial<br />by fire dive into web-dev.</p>
                        </div>
                    </div>

                    <div>
                        <h1 className={inter.className}><code className={styles.code}>$ cat in_dev.txt</code></h1>
                        <div className={styles.center}>
                            <p className={inter.className}>I will be building a more dynamic site, written with the T3 Stack with ThreeJS and Framer-Motion. <br />Employing typesafety and have agency throughout my DX, and I want to mess around with basic 3D graphic work.<br />I am also working on an EP, which I plan to release within the next few months.<br />Finally, I would like to create a VST before the summer, as well as some other smaller tools.</p>
                        </div>
                    </div>
                </div>

                <div className={styles.grid}>
                    <a
                        href="https://linkedin.com/in/jonah-perry/"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            LINKEDIN <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Look at me.
                        </p>
                    </a>

                    <a
                        href="https://soundcloud.com/astandardrobot"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            MUSIC <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Listen to stuff I made.
                        </p>
                    </a>

                    <a
                        href="https://github.com/astandardrobot/"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            Dev <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Download tools I designed/developed.
                        </p>
                    </a>

                    <a
                        href="https://github.com/astandardrobot/"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            VSTs <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Download DAW plugins I designed/developed.
                        </p>
                    </a>

                </div>
            </main>
        </>
    )
}
